import re
import unittest
from pathlib import Path


ROOT = Path("/Users/sammie/Desktop/new")


class ShellSpecTests(unittest.TestCase):
    def test_shell_files_exist(self) -> None:
        self.assertTrue((ROOT / "index.html").exists(), "index.html should exist")
        self.assertTrue((ROOT / "styles.css").exists(), "styles.css should exist")
        self.assertTrue((ROOT / "script.js").exists(), "script.js should exist")

    def test_html_has_three_panel_shell(self) -> None:
        html = (ROOT / "index.html").read_text()

        self.assertIn('class="terminal-shell"', html)
        self.assertIn('class="panel panel-left"', html)
        self.assertIn('class="panel-label" aria-hidden="true">1<', html)
        self.assertIn('class="panel-right-stack"', html)
        self.assertIn('class="panel panel-right"', html)
        self.assertIn('class="panel-label" aria-hidden="true">6<', html)
        self.assertIn('class="panel-6-log-shell"', html)
        self.assertIn('id="panel-6-status"', html)
        self.assertIn('id="panel-6-log"', html)
        self.assertIn('id="panel-6-empty"', html)
        self.assertIn('class="panel panel-right-bottom"', html)
        self.assertIn('class="panel-label" aria-hidden="true">7<', html)
        self.assertNotIn('class="panel-7-demo-actions"', html)
        self.assertNotIn('id="demo-sleep-in-class"', html)
        self.assertIn('class="left-panel-identity"', html)
        self.assertIn('class="portrait-frame"', html)
        self.assertIn('class="identity-name"', html)
        self.assertIn('class="identity-class"', html)
        self.assertIn('id="player-class-label"', html)
        self.assertIn('id="profile-first-name"', html)
        self.assertIn('id="profile-last-name"', html)
        self.assertIn('class="identity-first-name"', html)
        self.assertIn('class="identity-last-name"', html)
        self.assertIn('class="identity-rank"', html)
        self.assertIn('id="player-rank-label"', html)
        self.assertIn('class="identity-profile"', html)
        self.assertIn('id="player-personality-label"', html)
        self.assertIn('id="profile-gender-label"', html)
        self.assertIn('id="player-stat-strength"', html)
        self.assertIn('id="player-stat-intelligence"', html)
        self.assertIn('id="player-stat-fear"', html)
        self.assertIn('id="player-stat-reputation"', html)
        self.assertIn('class="panel-center-stack"', html)
        self.assertIn('class="panel panel-center-top"', html)
        self.assertIn('class="panel-label" aria-hidden="true">2<', html)
        self.assertIn('class="panel-center-main-stack"', html)
        self.assertIn('class="panel panel-center"', html)
        self.assertIn('class="panel-label" aria-hidden="true">3<', html)
        self.assertIn('class="panel panel-center-bottom"', html)
        self.assertIn('class="center-bottom-workspace"', html)
        self.assertIn('class="center-bottom-panel center-bottom-panel-left"', html)
        self.assertIn('class="center-bottom-panel center-bottom-panel-right"', html)
        self.assertIn('class="panel-label" aria-hidden="true">4<', html)
        self.assertIn('class="panel-label" aria-hidden="true">5<', html)
        self.assertIn('class="panel-4-controls"', html)
        self.assertIn('id="panel-4-sort"', html)
        self.assertIn('id="panel-4-filter-gender"', html)
        self.assertIn('id="panel-4-filter-affiliation"', html)
        self.assertIn('id="panel-4-filter-stat"', html)
        self.assertIn('id="panel-4-filter-stat-min"', html)
        self.assertIn('class="panel-4-list-header panel-4-table-grid"', html)
        self.assertIn('class="panel-4-list-heading">Name<', html)
        self.assertIn('class="panel-4-list-heading">Rank<', html)
        self.assertIn('class="panel-4-list-heading">Gender<', html)
        self.assertNotIn('class="panel-4-list-heading">Type<', html)
        self.assertIn('class="panel-4-list-heading">Stats<', html)
        self.assertNotIn('class="panel-4-list-heading">STR<', html)
        self.assertNotIn('class="panel-4-list-heading">FEAR<', html)
        self.assertIn('id="panel-4-npc-list"', html)
        self.assertIn('id="panel-4-empty"', html)
        self.assertIn('class="center-workspace"', html)
        self.assertIn('class="map-stage"', html)
        self.assertIn('class="map-coordinate-frame"', html)
        self.assertIn('class="map-axis map-axis-columns"', html)
        self.assertIn('class="map-axis map-axis-rows"', html)
        self.assertIn('class="map-axis-label">A<', html)
        self.assertIn('class="map-axis-label">B<', html)
        self.assertIn('class="map-axis-label">C<', html)
        self.assertIn('class="map-axis-label">D<', html)
        self.assertIn('class="map-axis-label">E<', html)
        self.assertIn('class="map-axis-label">F<', html)
        self.assertIn('class="map-axis-label">G<', html)
        self.assertIn('class="map-axis-label">H<', html)
        self.assertIn('class="map-axis-label">I<', html)
        self.assertIn('class="map-axis-label">J<', html)
        self.assertIn('class="map-axis-label">1<', html)
        self.assertIn('class="map-axis-label">2<', html)
        self.assertIn('class="map-axis-label">3<', html)
        self.assertIn('class="map-axis-label">4<', html)
        self.assertIn('class="map-axis-label">5<', html)
        self.assertIn('class="map-axis-label">6<', html)
        self.assertIn('class="map-axis-label">7<', html)
        self.assertIn('class="map-axis-label">8<', html)
        self.assertIn('class="map-axis-label">9<', html)
        self.assertIn('class="map-axis-label">10<', html)
        self.assertIn('class="map-grid"', html)
        self.assertIn('class="map-info-panel"', html)
        self.assertIn('id="map-info-coordinate"', html)
        self.assertIn('id="map-info-location-name"', html)
        self.assertIn('id="map-info-line-name"', html)
        self.assertIn('id="map-info-actions"', html)
        self.assertIn('id="map-action-study"', html)
        self.assertIn('id="map-action-sleep"', html)
        self.assertIn('id="map-action-observe"', html)
        self.assertNotIn('id="map-info-control"', html)
        self.assertNotIn('id="map-info-power"', html)
        self.assertIn('id="map-grid"', html)
        self.assertIn('id="dev-panel-toggle"', html)
        self.assertIn('class="dev-panel-handle"', html)
        self.assertIn('id="dev-panel"', html)
        self.assertIn('class="dev-panel"', html)
        self.assertIn('class="dev-panel-body"', html)
        self.assertIn('id="player-personality-select"', html)
        self.assertIn('for="theme-mode-select"', html)
        self.assertIn('id="theme-mode-select"', html)
        self.assertIn('aria-label="Theme mode"', html)
        self.assertIn('<script src="./script.js"></script>', html)

    def test_css_matches_terminal_layout(self) -> None:
        css = (ROOT / "styles.css").read_text()

        self.assertRegex(css, r"grid-template-columns:\s*25fr\s+50fr\s+25fr;")
        self.assertIn("--color-background: #050505;", css)
        self.assertIn("--color-border: #202020;", css)
        self.assertRegex(css, r"body\[data-theme=\"light\"\]\s*\{[^}]*--color-background:\s*#f2efe7;")
        self.assertRegex(css, r"body\[data-theme=\"light\"\]\s*\{[^}]*--color-panel:\s*#e9e4d8;")
        self.assertRegex(css, r"body\[data-theme=\"light\"\]\s*\{[^}]*--color-border:\s*#c9c1b2;")
        self.assertRegex(css, r"body\[data-theme=\"light\"\]\s*\{[^}]*--color-text:\s*#171512;")
        self.assertRegex(css, r"body\[data-theme=\"light\"\]\s*\{[^}]*--color-text-muted:\s*#6d665a;")
        self.assertRegex(css, r"body\[data-theme=\"light\"\]\s*\{[^}]*--color-gang-rival-dark:")
        self.assertIn("--color-gang-rival-light:", css)
        self.assertIn("--color-gang-rival-mid:", css)
        self.assertIn("--color-gang-rival-dark:", css)
        self.assertIn("--color-gang-player-light:", css)
        self.assertIn("--color-gang-player-mid:", css)
        self.assertIn("--color-gang-player-dark:", css)
        self.assertIn("IBM Plex Mono", css)
        self.assertRegex(css, r"height:\s*100svh;")
        self.assertIn("--dev-panel-width:", css)
        self.assertIn("--center-top-height:", css)
        self.assertIn("--center-bottom-height:", css)
        self.assertIn("--map-grid-size: 10;", css)
        self.assertIn("--map-cell-gap:", css)
        self.assertIn("--map-cell-inset:", css)
        self.assertIn("--map-info-width:", css)
        self.assertIn("--map-stage-width:", css)
        self.assertIn("--portrait-size:", css)
        self.assertRegex(css, r"\.panel-label\s*\{[^}]*position:\s*absolute;", re.S)
        self.assertRegex(css, r"\.panel-label\s*\{[^}]*top:\s*12px;", re.S)
        self.assertRegex(css, r"\.panel-label\s*\{[^}]*left:\s*12px;", re.S)
        self.assertRegex(css, r"\.panel-label\s*\{[^}]*color:\s*var\(--color-text-muted\);", re.S)
        self.assertRegex(css, r"\.panel-label\s*\{[^}]*font-size:\s*12px;", re.S)
        self.assertRegex(css, r"\.dev-panel-body\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.dev-panel-body\s*\{[^}]*padding:\s*56px\s+20px\s+20px;", re.S)
        self.assertRegex(css, r"\.panel-right-stack\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.panel-right-stack\s*\{[^}]*grid-template-rows:\s*minmax\(0,\s*1fr\)\s+min\(37\.5vw,\s*27rem\);", re.S)
        self.assertRegex(css, r"\.panel-right-stack\s*\{[^}]*min-height:\s*100svh;", re.S)
        self.assertRegex(css, r"\.panel-right-stack\s*\{[^}]*border-left:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.panel-right-stack\s*>\s*\.panel\s*\{[^}]*min-height:\s*0;", re.S)
        self.assertRegex(css, r"\.panel-right-bottom\s*\{[^}]*border-top:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.panel-right\s*\{[^}]*padding:\s*40px\s+24px\s+24px;", re.S)
        self.assertRegex(css, r"\.panel-6-log-shell\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.panel-6-log-shell\s*\{[^}]*height:\s*100%;", re.S)
        self.assertRegex(css, r"\.panel-6-status\s*\{[^}]*min-height:\s*16px;", re.S)
        self.assertRegex(css, r"\.panel-6-status\[data-locked=\"true\"\]\s*\{[^}]*color:\s*var\(--color-text\);", re.S)
        self.assertRegex(css, r"\.panel-6-log\s*\{[^}]*overflow-y:\s*auto;", re.S)
        self.assertRegex(css, r"\.panel-6-log\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.log-entry\s*\{[^}]*border:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.log-entry-progress\s*\{[^}]*height:\s*8px;", re.S)
        self.assertRegex(css, r"\.log-entry-progress\s*\{[^}]*border:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.log-entry-progress-fill\s*\{[^}]*width:\s*0;", re.S)
        self.assertRegex(css, r"\.log-entry-progress-fill\s*\{[^}]*background:\s*#d8d8d8;", re.S)
        self.assertNotIn(".log-entry-progress-meta", css)
        self.assertNotIn(".log-entry-progress-value", css)
        self.assertRegex(css, r"\.log-decision-buttons\s*\{[^}]*display:\s*flex;", re.S)
        self.assertRegex(css, r"\.log-choice-button\s*\{[^}]*border:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.panel-right-bottom\s*\{[^}]*padding:\s*40px\s+24px\s+24px;", re.S)
        self.assertNotIn(".panel-7-demo-actions", css)
        self.assertNotIn(".demo-action-button", css)
        self.assertRegex(css, r"\.panel-4-npc-shell\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.panel-4-npc-shell\s*\{[^}]*padding-top:\s*0;", re.S)
        self.assertRegex(css, r"\.panel-4-controls\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.panel-4-controls\s*\{[^}]*grid-template-columns:\s*1\.15fr\s+0\.8fr\s+0\.8fr\s+0\.8fr\s+3\.4rem;", re.S)
        self.assertRegex(css, r"\.panel-4-control\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.panel-4-control\s*\{[^}]*align-content:\s*start;", re.S)
        self.assertRegex(css, r"\.panel-4-control-input\s*\{[^}]*border:\s*0;", re.S)
        self.assertRegex(css, r"\.panel-4-control-input\s*\{[^}]*border-bottom:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"#panel-4-filter-stat-min\s*\{[^}]*appearance:\s*textfield;", re.S)
        self.assertRegex(css, r"#panel-4-filter-stat-min::-webkit-inner-spin-button,\s*#panel-4-filter-stat-min::-webkit-outer-spin-button\s*\{[^}]*-webkit-appearance:\s*none;", re.S)
        self.assertRegex(css, r"\.panel-4-table-grid\s*\{[^}]*grid-template-columns:\s*minmax\(6\.5rem,\s*1\.15fr\)\s+minmax\(4rem,\s*0\.55fr\)\s+minmax\(5\.5rem,\s*0\.9fr\)\s+minmax\(7rem,\s*1fr\);", re.S)
        self.assertRegex(css, r"\.panel-4-list-header\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.panel-4-list-header\s*\{[^}]*border-bottom:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.panel-4-npc-list\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.panel-4-empty-state\s*\{[^}]*color:\s*var\(--color-text-muted\);", re.S)
        self.assertRegex(css, r"\.panel-4-npc-entry\s*\{[^}]*border-bottom:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.panel-4-npc-entry\s*\{[^}]*cursor:\s*pointer;", re.S)
        self.assertRegex(css, r"\.panel-4-npc-entry\[data-selected=\"true\"\]\s*\{[^}]*background:\s*#090909;", re.S)
        self.assertRegex(css, r"\.panel-4-npc-cell\s*\{[^}]*min-width:\s*0;", re.S)
        self.assertRegex(css, r"\.panel-4-npc-cell\s*\{[^}]*overflow:\s*hidden;", re.S)
        self.assertRegex(css, r"\.panel-4-npc-name\s*\{[^}]*color:\s*var\(--color-text\);", re.S)
        self.assertRegex(css, r"\.panel-4-npc-stat\s*\{[^}]*text-align:\s*right;", re.S)
        self.assertRegex(css, r"\.center-bottom-panel\s*\{[^}]*position:\s*relative;", re.S)
        self.assertRegex(css, r"\.center-bottom-panel-right\s*>\s*\.panel-label\s*\{[^}]*left:\s*24px;", re.S)
        self.assertRegex(css, r"\.left-panel-identity\s*\{[^}]*grid-template-columns:\s*var\(--portrait-size\)\s+minmax\(0,\s*1fr\);", re.S)
        self.assertRegex(css, r"\.left-panel-identity\s*\{[^}]*align-items:\s*start;", re.S)
        self.assertRegex(css, r"\.left-panel-identity\s*\{[^}]*padding:\s*24px;", re.S)
        self.assertRegex(css, r"\.portrait-frame\s*\{[^}]*width:\s*var\(--portrait-size\);", re.S)
        self.assertRegex(css, r"\.portrait-frame\s*\{[^}]*aspect-ratio:\s*3\s*/\s*4;", re.S)
        self.assertRegex(css, r"\.identity-class\s*\{[^}]*color:\s*var\(--color-text-muted\);", re.S)
        self.assertRegex(css, r"\.identity-class\s*\{[^}]*font-size:\s*11px;", re.S)
        self.assertRegex(css, r"\.identity-class\s*\{[^}]*text-transform:\s*uppercase;", re.S)
        self.assertRegex(css, r"\.identity-name\s*\{[^}]*text-transform:\s*uppercase;", re.S)
        self.assertRegex(css, r"\.identity-rank\s*\{[^}]*padding-top:\s*12px;", re.S)
        self.assertRegex(css, r"\.identity-rank\s*\{[^}]*border-top:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.identity-rank-label\s*\{[^}]*font-size:\s*13px;", re.S)
        self.assertRegex(css, r"\.identity-rank-label\s*\{[^}]*text-transform:\s*uppercase;", re.S)
        self.assertRegex(css, r"\.identity-profile\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.identity-profile\s*\{[^}]*gap:\s*12px;", re.S)
        self.assertRegex(css, r"\.identity-profile\s*\{[^}]*padding-top:\s*12px;", re.S)
        self.assertRegex(css, r"\.identity-profile\s*\{[^}]*border-top:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.identity-field-value\s*\{[^}]*color:\s*var\(--color-text\);", re.S)
        self.assertRegex(css, r"\.identity-field-value\s*\{[^}]*font-size:\s*13px;", re.S)
        self.assertRegex(css, r"\.identity-select\s*\{[^}]*border:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.identity-select\s*\{[^}]*background:\s*var\(--color-background\);", re.S)
        self.assertRegex(css, r"\.identity-stats\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.identity-stat\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto;", re.S)
        self.assertRegex(css, r"\.identity-stat-label\s*\{[^}]*color:\s*var\(--color-text-muted\);", re.S)
        self.assertRegex(css, r"\.identity-stat-value\s*\{[^}]*color:\s*var\(--color-text\);", re.S)
        self.assertRegex(css, r"\.panel-center-stack\s*\{[^}]*grid-template-rows:\s*var\(--center-top-height\)\s+minmax\(0,\s*1fr\);", re.S)
        self.assertRegex(css, r"\.panel-center-stack\s*\{[^}]*border-left:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.panel-center-main-stack\s*\{[^}]*grid-template-rows:\s*fit-content\(100%\)\s+minmax\(var\(--center-bottom-height\),\s*1fr\);", re.S)
        self.assertRegex(css, r"\.panel-center-main-stack\s*\{[^}]*height:\s*100%;", re.S)
        self.assertRegex(css, r"\.panel-center-main-stack\s*\{[^}]*align-content:\s*start;", re.S)
        self.assertRegex(css, r"\.panel-center\s*\{[^}]*height:\s*fit-content;", re.S)
        self.assertRegex(css, r"\.panel-center\s*\{[^}]*padding:\s*24px;", re.S)
        self.assertRegex(css, r"\.center-workspace\s*\{[^}]*grid-template-columns:\s*var\(--map-stage-width\)\s+var\(--map-info-width\);", re.S)
        self.assertRegex(css, r"\.center-workspace\s*\{[^}]*gap:\s*24px;", re.S)
        self.assertRegex(css, r"\.center-workspace\s*\{[^}]*width:\s*fit-content;", re.S)
        self.assertRegex(css, r"\.center-workspace\s*\{[^}]*height:\s*fit-content;", re.S)
        self.assertRegex(css, r"\.map-stage\s*\{[^}]*justify-self:\s*start;", re.S)
        self.assertRegex(css, r"\.map-stage\s*\{[^}]*width:\s*var\(--map-stage-width\);", re.S)
        self.assertRegex(css, r"\.map-coordinate-frame\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.map-coordinate-frame\s*\{[^}]*grid-template-columns:\s*20px\s+minmax\(0,\s*1fr\);", re.S)
        self.assertRegex(css, r"\.map-coordinate-frame\s*\{[^}]*grid-template-rows:\s*20px\s+minmax\(0,\s*1fr\);", re.S)
        self.assertRegex(css, r"\.map-coordinate-frame\s*\{[^}]*gap:\s*12px;", re.S)
        self.assertRegex(css, r"\.map-axis-columns\s*\{[^}]*grid-template-columns:\s*repeat\(var\(--map-grid-size\),\s*minmax\(0,\s*1fr\)\);", re.S)
        self.assertRegex(css, r"\.map-axis-rows\s*\{[^}]*grid-template-rows:\s*repeat\(var\(--map-grid-size\),\s*minmax\(0,\s*1fr\)\);", re.S)
        self.assertRegex(css, r"\.map-axis-label\s*\{[^}]*font-size:\s*12px;", re.S)
        self.assertRegex(css, r"\.map-axis-label\s*\{[^}]*color:\s*var\(--color-text-muted\);", re.S)
        self.assertRegex(css, r"\.map-axis-columns\s*\.map-axis-label\s*\{[^}]*color:\s*var\(--color-text\);", re.S)
        self.assertRegex(css, r"\.map-axis-columns\s*\.map-axis-label\s*\{[^}]*font-size:\s*13px;", re.S)
        self.assertNotRegex(css, r"\.map-info-panel\s*\{[^}]*border-left:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.map-info-panel\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.map-info-panel\s*\{[^}]*align-content:\s*start;", re.S)
        self.assertRegex(css, r"\.map-info-panel\s*\{[^}]*gap:\s*12px;", re.S)
        self.assertRegex(css, r"\.map-info-panel\s*\{[^}]*padding-top:\s*32px;", re.S)
        self.assertRegex(css, r"\.map-info-actions\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.map-info-actions\s*\{[^}]*gap:\s*8px;", re.S)
        self.assertRegex(css, r"\.map-info-actions\[hidden\]\s*\{[^}]*display:\s*none;", re.S)
        self.assertRegex(css, r"\.map-info-action-button\s*\{[^}]*border:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.map-info-line-value\s*\{[^}]*min-height:\s*1\.2em;", re.S)
        self.assertRegex(css, r"\.map-grid\s*\{[^}]*grid-template-columns:\s*repeat\(var\(--map-grid-size\),\s*minmax\(0,\s*1fr\)\);", re.S)
        self.assertRegex(css, r"\.map-grid\s*\{[^}]*aspect-ratio:\s*1\s*/\s*1;", re.S)
        self.assertRegex(css, r"\.map-cell\s*\{[^}]*border:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.map-cell::before\s*\{[^}]*content:\s*\"\";", re.S)
        self.assertRegex(css, r"\.map-cell::before\s*\{[^}]*position:\s*absolute;", re.S)
        self.assertRegex(css, r"\.map-cell::before\s*\{[^}]*inset:\s*var\(--map-cell-inset\);", re.S)
        self.assertRegex(css, r"\.map-cell::before\s*\{[^}]*background:\s*var\(--map-cell-fill,\s*transparent\);", re.S)
        self.assertRegex(css, r"\.map-cell\[data-controller=\"rival\"\]\[data-power=\"high\"\]\s*\{[^}]*--map-cell-fill:\s*var\(--color-gang-rival-dark\);", re.S)
        self.assertRegex(css, r"\.map-cell\[data-controller=\"rival\"\]\[data-power=\"medium\"\]\s*\{[^}]*--map-cell-fill:\s*var\(--color-gang-rival-mid\);", re.S)
        self.assertRegex(css, r"\.map-cell\[data-controller=\"rival\"\]\[data-power=\"low\"\]\s*\{[^}]*--map-cell-fill:\s*var\(--color-gang-rival-light\);", re.S)
        self.assertRegex(css, r"\.map-cell:hover\s*\{[^}]*border-color:\s*var\(--color-text-muted\);", re.S)
        self.assertRegex(css, r"\.map-cell\[data-selected=\"true\"\]\s*\{[^}]*border-color:\s*var\(--color-text\);", re.S)
        self.assertRegex(css, r"\.panel-center-bottom\s*\{[^}]*border-top:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.center-bottom-workspace\s*\{[^}]*display:\s*grid;", re.S)
        self.assertRegex(css, r"\.center-bottom-workspace\s*\{[^}]*grid-template-columns:\s*1fr\s+1fr;", re.S)
        self.assertRegex(css, r"\.center-bottom-workspace\s*\{[^}]*gap:\s*24px;", re.S)
        self.assertRegex(css, r"\.center-bottom-workspace\s*\{[^}]*padding:\s*24px;", re.S)
        self.assertRegex(css, r"\.center-bottom-workspace\s*\{[^}]*align-items:\s*stretch;", re.S)
        self.assertRegex(css, r"\.center-bottom-panel\s*\{[^}]*min-height:\s*100%;", re.S)
        self.assertRegex(css, r"\.panel-center-bottom\s*\{[^}]*position:\s*relative;", re.S)
        self.assertRegex(css, r"\.panel-center-top\s*\{[^}]*border-bottom:\s*1px\s+solid\s+var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.panel-center-bottom::before\s*\{[^}]*content:\s*\"\";", re.S)
        self.assertRegex(css, r"\.panel-center-bottom::before\s*\{[^}]*position:\s*absolute;", re.S)
        self.assertRegex(css, r"\.panel-center-bottom::before\s*\{[^}]*top:\s*0;", re.S)
        self.assertRegex(css, r"\.panel-center-bottom::before\s*\{[^}]*bottom:\s*0;", re.S)
        self.assertRegex(css, r"\.panel-center-bottom::before\s*\{[^}]*left:\s*50%;", re.S)
        self.assertRegex(css, r"\.panel-center-bottom::before\s*\{[^}]*width:\s*1px;", re.S)
        self.assertRegex(css, r"\.panel-center-bottom::before\s*\{[^}]*background:\s*var\(--color-border\);", re.S)
        self.assertRegex(css, r"\.dev-panel\s*\{[^}]*transform:\s*translateX\(100%\);", re.S)
        self.assertRegex(
            css,
            r"#dev-panel-toggle:checked\s*\+\s*\.dev-panel-handle\s*\+\s*\.dev-panel\s*\{[^}]*transform:\s*translateX\(0\);",
            re.S,
        )

    def test_script_builds_interactive_map(self) -> None:
        script = (ROOT / "script.js").read_text()

        self.assertIn("const RANKS = Object.freeze([", script)
        self.assertIn("const PERSONALITIES = Object.freeze([", script)
        self.assertIn("const GENDERS = Object.freeze([", script)
        self.assertIn('id: "male"', script)
        self.assertIn('id: "female"', script)
        self.assertIn('id: "impulsive"', script)
        self.assertIn('id: "calculating"', script)
        self.assertIn('id: "schemer"', script)
        self.assertIn('id: "detached"', script)
        self.assertIn('id: "devoted"', script)
        self.assertIn("const STAT_KEYS = Object.freeze([", script)
        self.assertIn('id: "nobody"', script)
        self.assertIn('id: "jjang"', script)
        self.assertIn('function getRank(rankId)', script)
        self.assertIn("function getPersonality(personalityId)", script)
        self.assertIn("function getGender(genderId)", script)
        self.assertIn("function normalizeStats(stats = {})", script)
        self.assertIn("function createCharacter({", script)
        self.assertIn('personalityId = "detached"', script)
        self.assertIn('gender = "male"', script)
        self.assertIn('gangId = ""', script)
        self.assertIn("stats = {}", script)
        self.assertIn('className = ""', script)
        self.assertIn("const gameState = {", script)
        self.assertIn("player: createCharacter({", script)
        self.assertIn("className: \"Class 1\"", script)
        self.assertIn('personalityId: "detached"', script)
        self.assertIn("stats: {", script)
        self.assertIn("npcs: [", script)
        self.assertIn('firstName: "Si-heon"', script)
        self.assertIn('lastName: "Nam"', script)
        self.assertIn('gender: "male"', script)
        self.assertIn('gangId: ""', script)
        self.assertIn('locationCoordinate: "B2"', script)
        self.assertIn("isRecruited: false", script)
        self.assertIn("const LOCATION_DATA = {", script)
        self.assertIn('B2: {', script)
        self.assertIn('name: "Class 1"', script)
        self.assertIn('lineName: ""', script)
        self.assertIn('controller: "rival"', script)
        self.assertIn('power: "high"', script)
        self.assertIn('document.getElementById("player-class-label")', script)
        self.assertIn('document.getElementById("profile-first-name")', script)
        self.assertIn('document.getElementById("profile-last-name")', script)
        self.assertIn('document.getElementById("player-rank-label")', script)
        self.assertIn('document.getElementById("player-personality-label")', script)
        self.assertIn('document.getElementById("profile-gender-label")', script)
        self.assertIn('document.getElementById("player-personality-select")', script)
        self.assertIn('document.getElementById("theme-mode-select")', script)
        self.assertIn('document.getElementById("player-stat-strength")', script)
        self.assertIn('document.getElementById("player-stat-intelligence")', script)
        self.assertIn('document.getElementById("player-stat-fear")', script)
        self.assertIn('document.getElementById("player-stat-reputation")', script)
        self.assertIn('document.getElementById("map-info-coordinate")', script)
        self.assertIn('document.getElementById("map-info-location-name")', script)
        self.assertIn('document.getElementById("map-info-line-name")', script)
        self.assertIn('document.getElementById("map-info-actions")', script)
        self.assertIn('document.getElementById("map-action-study")', script)
        self.assertIn('document.getElementById("map-action-sleep")', script)
        self.assertIn('document.getElementById("map-action-observe")', script)
        self.assertIn('document.getElementById("panel-4-npc-list")', script)
        self.assertIn('document.getElementById("panel-4-empty")', script)
        self.assertIn('document.getElementById("panel-4-sort")', script)
        self.assertIn('document.getElementById("panel-4-filter-gender")', script)
        self.assertIn('document.getElementById("panel-4-filter-affiliation")', script)
        self.assertIn('document.getElementById("panel-4-filter-stat")', script)
        self.assertIn('document.getElementById("panel-4-filter-stat-min")', script)
        self.assertIn('document.getElementById("panel-6-status")', script)
        self.assertIn('document.getElementById("panel-6-log")', script)
        self.assertIn('document.getElementById("panel-6-empty")', script)
        self.assertNotIn('document.getElementById("demo-sleep-in-class")', script)
        self.assertNotIn('document.getElementById("map-info-control")', script)
        self.assertNotIn('document.getElementById("map-info-power")', script)
        self.assertIn("const ACTION_DEFINITIONS = {", script)
        self.assertIn("const pendingDecisions = new Set();", script)
        self.assertIn("function getProfileCharacter()", script)
        self.assertIn("function selectProfileCharacter(characterId)", script)
        self.assertIn("function getAffiliation(character)", script)
        self.assertIn("function getAffiliationLabel(character)", script)
        self.assertIn("function getPanel4Filters()", script)
        self.assertIn("function passesNpcFilters(npc)", script)
        self.assertIn("function sortNpcsForPanel4(npcs)", script)
        self.assertIn("function formatNpcStats(npc)", script)
        self.assertIn("function formatLineName(location)", script)
        self.assertIn("function formatCharacterName(character)", script)
        self.assertIn("function isPlayersClassLocation(location)", script)
        self.assertIn("function getUnrecruitedNpcsForCoordinate(coordinate)", script)
        self.assertIn("function syncPlayerProfile()", script)
        self.assertIn("function syncAvailableNpcs()", script)
        self.assertIn('entry.type = "button";', script)
        self.assertIn("entry.dataset.characterId = npc.id;", script)
        self.assertIn('entry.dataset.selected = npc.id === gameState.profileCharacterId ? "true" : "false";', script)
        self.assertIn('function createPanel4Cell(text, className = "")', script)
        self.assertIn("function formatNpcStatsSummary(npc)", script)
        self.assertIn('"panel-4-npc-name"', script)
        self.assertIn('"panel-4-npc-stat"', script)
        self.assertIn("createPanel4Cell(getGender(npc.gender).label)", script)
        self.assertNotIn("const typeSummary =", script)
        self.assertIn("entry.append(", script)
        self.assertIn('entry.addEventListener("click"', script)
        self.assertIn("selectProfileCharacter(npc.id);", script)
        self.assertIn('panel4Sort.addEventListener("change"', script)
        self.assertIn('panel4GenderFilter.addEventListener("change"', script)
        self.assertIn('panel4AffiliationFilter.addEventListener("change"', script)
        self.assertIn('panel4StatFilter.addEventListener("change"', script)
        self.assertIn('panel4StatMinFilter.addEventListener("input"', script)
        self.assertIn("function createLogEntry(", script)
        self.assertIn("function syncLogEmptyState()", script)
        self.assertIn("function syncDecisionLockState()", script)
        self.assertIn("function syncActionButtonAvailability(", script)
        self.assertIn("function startAction(", script)
        self.assertIn("function maybeCreateDecision(", script)
        self.assertIn("function resolveDecision(", script)
        self.assertIn("function syncPlayerRank()", script)
        self.assertIn('playerPersonalitySelect.addEventListener("change"', script)
        self.assertIn("function applyThemeMode(themeMode)", script)
        self.assertIn("document.body.dataset.theme = themeMode;", script)
        self.assertIn('themeModeSelect.addEventListener("change"', script)
        self.assertIn("function toCoordinate(row, column)", script)
        self.assertIn("function getLocationForCoordinate(coordinate)", script)
        self.assertIn("function syncMapInfo()", script)
        self.assertRegex(script, r"const GRID_SIZE = 10;")
        self.assertIn('document.getElementById("map-grid")', script)
        self.assertIn('document.createElement("button")', script)
        self.assertIn('grid.addEventListener("click"', script)
        self.assertIn('grid.addEventListener("keydown"', script)
        self.assertIn('function selectCell(index)', script)


if __name__ == "__main__":
    unittest.main()
